/**
 * WARNING: This file is generated by typed-i18next-loader. Do not modify it manually.
 */

import { CustomTypeOptions } from 'i18next'

declare module 'virtual:i18next-typed-loader' {
  const resources: {
    'en': CustomTypeOptions['resources']
    'en-GB': CustomTypeOptions['resources']
  }

  export default resources
}
