// WARNING: This file is auto-generated by vite-plugin-typed-i18next-loader. Do not edit it manually.

import 'i18next'

type FlatGeneratedResource<TResource, TNamespace extends keyof TResource> = {
  [SubProperty in keyof TResource[TNamespace] as `${string & TNamespace}:${string & SubProperty}`]: TResource[TNamespace][SubProperty]
};

type GeneratedResources = {
  'namespace': {
    'message': string
    'other': string
  }
  'translation': {
    'app.title': string
  }
}

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation'
    resources: GeneratedResources
      & { 'translation': FlatGeneratedResource<GeneratedResources, 'namespace'> }
      & { 'translation': FlatGeneratedResource<GeneratedResources, 'translation'> }
  }
}
