// WARNING: This file is auto-generated by vite-plugin-typed-i18next-loader. Do not edit it manually.

import 'i18next'

type GeneratedResources = {
  'namespace': {
    'message': string
    'other': string
  }
  'translation': {
    'app.title': string
  }
}

type FlatGeneratedResources<TResource, NS extends keyof TResource> = {
  [Property in keyof TResource[NS] as `${NS & string}:${Property & string}`]: TResource[NS][Property]
}

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation'
    resources: GeneratedResources
      & { 'translation': FlatGeneratedResources<GeneratedResources, 'namespace'> }
      & { 'translation': FlatGeneratedResources<GeneratedResources, 'translation'> }
  }
}
