// WARNING: This file is auto-generated by vite-plugin-typed-i18next-loader. Do not edit it manually.

import 'i18next'

type GeneratedResources = {
  'namespace': {
    'message': string
    'other': string
  }
  'translation': {
    'app.title': string
  }
}

type FlatGeneratedResources = {
  [Namespace in keyof GeneratedResources]: GeneratedResources[Namespace] extends object
    ? { [Property in keyof GeneratedResources[Namespace] as `${Namespace & string}:${Property & string}`]: GeneratedResources[Namespace][Property] }
    : { [Property in Namespace & string]: GeneratedResources[Namespace] }
}[keyof GeneratedResources];

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation'
    resources: GeneratedResources & { 'translation': FlatGeneratedResources }
  }
}

type VirtualTypedLoader = {
  'en': GeneratedResources
  'en-GB': GeneratedResources
}

declare module 'virtual:i18next-typed-loader' {
  export default VirtualTypedLoader
}
