/**
 * WARNING: This file is generated by typed-i18next-loader. Do not modify it manually.
 */

import 'i18next'

type GeneratedResources = {
  'message': {
    '0': string
    '1': string
    '2': string
    '3': string
    '4': string
    '5': string
    '6': string
    '7': string
    '8': string
    '9': string
    '10': string
    '11': string
    '12': string
  }
}

type FlatGeneratedResources<TResource, NS extends keyof TResource> = {
  [Property in keyof TResource[NS] as `${NS & string}:${Property & string}`]: TResource[NS][Property]
}

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation'
    resources: GeneratedResources
      & { 'translation': FlatGeneratedResources<GeneratedResources, 'message'> }
  }
}
